# Updated deployment.yaml for Keycloak
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:23.0.0
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin123"
        - name: KC_PROXY
          value: "edge"
        # Remove the auth path - modern Keycloak doesn't use /auth by default
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        ports:
        - name: http
          containerPort: 8080
        #readinessProbe:
        #  httpGet:
        #    path: /health/ready
        #    port: 8080
        #  initialDelaySeconds: 30
        #  periodSeconds: 10
        #livenessProbe:
        #  httpGet:
        #    path: /health/live
        #    port: 8080
        #  initialDelaySeconds: 60
        #  periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"