apiVersion: v1
kind: Service
metadata:
  name: argocd-repo-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-repo-server
spec:
  selector:
    app.kubernetes.io/name: argocd-repo-server
  ports:
    - name: https-repo-server
      port: 8081
      targetPort: 8081
      protocol: TCP
